# Generated by Django 5.2.3 on 2025-06-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=25, help_text='Montant of the transaction', max_digits=30),
            preserve_default=False,
        ),
    ]
