# Generated by Django 5.2.3 on 2025-06-20 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_detection', '0001_initial'),
        ('transactions', '0002_transaction_montant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagetransaction',
            name='transactionid',
        ),
        migrations.AddField(
            model_name='imagetransaction',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='image_transactions', to='transactions.transaction'),
            preserve_default=False,
        ),
    ]
